Repository dscigdtuw/DSC-HacktoberFest2020, pull requests merged in 2020-10, with the labels that each got.

#1 Updated addInfo and README.md
  README.md
  code/Java/Fibonacci.java
  code/addInfo.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020, hactober-accepted

#3 Add code
  README.md
  code/Longest_common_subsequence.java
  code/addInfo.json
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#7 Update README.md
  README.md
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#8 Create helloworld.cpp
  code/CPP/helloworld.cpp
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#9 Update helloworld.cpp
  code/CPP/helloworld.cpp
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#10 Update helloworld.cpp
  code/CPP/helloworld.cpp
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#4 Add code
  README.md
  code/Java/fibo.java
  code/addInfo.json
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#34 Added cpp code to detect loop in linked list
  code/CPP/detect_loop_linked_list.cpp
Labels: hacktober-accepted, hacktoberfest2020

#35 Update addInfo.json
  code/addInfo.json
Labels: hacktober-accepted, hacktoberfest-accepted

#36 BFS.cpp
  code/CPP/BFS.cpp
Labels: hacktoberfest-accepted, hacktoberfest2020

#37 Create getMaxOccuringChar.cpp
  code/CPP/getMaxOccuringChar.cpp
Labels: hacktober-accepted, hacktoberfest2020

#38 Create NaivePatternSearch.cpp
  code/CPP/NaivePatternSearch.cpp
Labels: hacktoberfest2020, hactober-accepted

#40 Create modifiedstr.cpp
  code/CPP/modifiedstr.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#45 added sudoku code in java
  code/Java/Sudoku.java
  code/addInfo.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#46 postfromin&pre
  code/CPP/postorderfromin&pre.cpp
  code/addInfo.json
Labels: hacktoberfest

#48 Added Sparse Matrix Code
  code/CPP/SparseMatrixinTriplet.cpp
  code/addInfo.json
Labels: hacktober-accepted, hacktoberfest2020

#49 Create NQueenProblem.cpp
  code/CPP/NQueenProblem.cpp
Labels: hacktober-accepted, hacktoberfest, hacktoberfest2020

#52 Added C Programs folder and a program to determine the type of triangle
  .DS_Store
  code/.DS_Store
  code/C Programs/.DS_Store
  code/C Programs/Triangle.c
  code/C Programs/Triangle.h
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#53 Added algorithm for Inverting case of a character
  code/CPP/InvertCase.cpp
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2020

#54 Added algo for longest bitonic subsequence
  code/CPP/LongestBitonicSubsequence.cpp
Labels: hacktober-accepted, hacktoberfest2020

#55 Added algorithm for making string anagrams
  Making_String_Anagrams.cpp
Labels: hacktober-accepted, hacktoberfest2020

#50 Update addInfo.json
  code/addInfo.json
Labels: hacktoberfest, hactober-accepted

#58 File moved to CPP folder
  code/CPP/Making_String_Anagrams.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#59 Rename code/human_readable_time.py to code/Python/human_readable_time.py
  code/Python/human_readable_time.py
Labels: hacktober-accepted

#60 CircularQueue
  README.md
  code/CPP/CircularQueue.cpp
  code/addInfo.json
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#61 Number System Conversion Added in Java, 2D Array codes incpp
  code/CPP/Array multiplication, wave print.cpp
  code/Java/numberSystem.java
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted

#62 Create remove_vowels.py
  code/Python/remove_vowels.py
Labels: hacktober-accepted, hacktoberfest2020

#66 Longest Zigzag Subsequence in Java added
  code/Java/longest_zigzag_subsq.java
Labels: hacktoberfest-accepted, hacktoberfest2020, hactober-accepted

#47 Update addInfo.json
  code/addInfo.json
Labels: hacktober-accepted

#67 Create quicksort_recursive.cpp
  code/CPP/quicksort_recursive.cpp
Labels: hacktober-accepted, hacktoberfest, hacktoberfest2020

#68 Create GaneshaPattern.cpp
  code/CPP/GaneshaPattern.cpp
Labels: hacktoberfest-accepted, hacktoberfest2020, hactober-accepted

#69 Create mergeSort.cpp
  code/CPP/mergeSort.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#70 Create dijkstra_algo.cpp
  code/CPP/dijkstra_algo.cpp
Labels: hacktoberfest-accepted, hacktoberfest2020

#71 Basic codes for Recursion like Tower of Hanoi
  code/Java/recursion.java
Labels: hacktoberfest-accepted, hacktoberfest2020

#63 Update README.md
  README.md
Labels: hacktober-accepted, hacktoberfest-accepted

#72 Patterns in Java
  code/CPP/checkers.cpp
  code/Java/diamond.java
Labels: hacktober-accepted, hacktoberfest, hacktoberfest2020

#75 Moved Longest_common_subsequence.java from code/Longest_common_subseq…
  code/Java/Longest_common_subsequence.java
Labels: hacktober-accepted, hacktoberfest-accepted

#73 C program added
  README.md
  code/C Programs/pair_sum.c
  code/addInfo.json
Labels: hacktober-accepted, hacktoberfest-accepted

#82 Added sorting algorithms in c programs folder
  code/C Programs/BubbleSort.c
  code/C Programs/SelectionSort.c
Labels: hacktober-accepted, hacktoberfest-accepted

#81 added 2D Array questions of java in java folder
  code/Java/ExitPointOfaMatrix.java
  code/Java/WaveTraversal.java
Labels: hacktober-accepted, hacktoberfest-accepted

#80 added String question in cpp folder
  code/CPP/PrintAllPermutationsWithRepetitionOfCharacters.cpp
  code/CPP/ReturnMaximumOccurrinCharacterInAnInputString.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#79 Shortest Common SuperSequence in Java
  code/Java/Shortest_Common_SuperSequence.java
Labels: hacktober-accepted, hacktoberfest-accepted

#65 to get the largest number
  miles to meter converter
  to get the largest number
Labels: hacktober-accepted, hacktoberfest-accepted

#76 Contributed for hacktoberfest 2020
  README.md
  code/CPP/binary_search.cpp
  code/addInfo.json
Labels: hacktober-accepted, hacktoberfest-accepted

#77 Add files via upload
  code/C Programs/linear_search.c
Labels: hacktober-accepted, hacktoberfest-accepted

#83 dollar to indian rupee converter
  dollar to indian rupee converter
Labels: hacktober-accepted, hacktoberfest-accepted

#84 fibonacci.cpp
  fibonacci.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#86 Move files to their respective folders
  code/CPP/fibonacci.cpp
  code/dollar to indian rupee converter
  code/miles to meter converter
  code/to get the largest number
Labels: hacktober-accepted, hacktoberfest

#89 mitali
  README.md
  code/CPP/linear_search.cpp
  code/addInfo.json
Labels: hacktoberfest-accepted

#87 Rotating 1D array
  README.md
  code/Java/Rotating an Array.java
  code/addInfo.json
Labels: hacktober-accepted, hacktoberfest-accepted

#88 Mitali
  README.md
  code/CPP/reverse_array_in_groups.cpp
  code/addInfo.json
Labels: hacktoberfest-accepted
